movieproject/movieapp/urls.py
from django.urls import path

from . import views
app_name = 'movieapp'
urlpatterns=[
    path('',views.index,name='index'),
    path('details/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.movie_add, name='movie_add'),
    path('update/<int:movie_id>/', views.update, name='update'),
    path('delete/<int:movie_id>/', views.delete, name='delete'),

]

movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from movieproject import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls")),

]

if settings.DEBUG:
            urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
            urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img = models.ImageField(upload_to='MOVIEMEDIA')

    def __str__(self):
        return self.name

movieproject/movieapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .form import Movie_Form
# Create your views here.
from .models import Movie
from django.shortcuts import render, redirect

def index(request):
    movie = Movie.objects.all()
    return render(request, 'index.html', {'movie': movie})


def detail(request, movie_id):
        movie = Movie.objects.get(id=movie_id)
        return render(request, 'detail.html', {'movie': movie})


def movie_add(request):
    if request.method == "POST":
        name = request.POST['name']
        desc = request.POST['desc']
        year=request.POST['year']
        img = request.FILES['img']
        movie = Movie(name=name,desc=desc,year=year ,img=img)
        movie.save()
    return render(request, 'add.html')



def delete(request, movie_id):
        if request.method == 'POST':
            movie = Movie.objects.get(id=movie_id)
            movie.delete()
            return redirect('/')

        return render(request, 'delete.html')

def update(request, movie_id):
            movie = Movie.objects.get(id=movie_id)
            form = Movie_Form(request.POST or None, request.FILES, instance=movie)

            if form.is_valid():
                form.save()
                return redirect('/')

            return render(request, 'update.html', {'form': form, 'movie': movie})

movieproject/templates/add.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>Add Movie</title>
</head>
<body>
{% extends 'base.html' %}
{% block body %}


<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter the movie name"><br>
    <input type="text" name="desc" placeholder="Enter the description"><br>
    <input type="number" name="year" placeholder="Enter the movie year"><br>
    <input type="file" name="img"><br>
    <input type="submit">

</form>
{% endblock %}
</body>
</html>

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>

  <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'movieapp:index' %}">MOVIE HUB</a>
  </div>
</nav>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
{% extends 'base.html' %}
{% block body %}
<form method="post">
  {% csrf_token %}
    Are you sure? <br>
<input type="submit" value="Yes">

</form>
{% endblock %}
</body>
</html>

movieproject/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>

</head>
<body>
    {% extends 'base.html' %}
    {% block body %}
    <div class="center-content">


        <h2>{{movie.name}}</h2><br>
        <img src="{{movie.img.url}}" width="200" height="400"><br>
        {{movie.desc}}<br>
        <br>{{movie.year}}<br>
        <a class="btn btn-primary" href="{% url 'movieapp:update' movie.id %} " >Update</a><br><br>
        <a class="btn btn-primary" href="{% url 'movieapp:delete' movie.id %}" >Delete</a>

    </div>
     {% endblock %}
</body>
</html>

movieproject/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie</title>
</head>
<body>
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie %}
        <div class="col-md-3">
            <div class="card custom-card" style="width: 100%;height:100;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="202" height="400">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Detail</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<center><a href="{% url 'movieapp:movie_add' %}" class="btn btn-primary">Add New</a> </center>
{% endblock %}
</body>
</html>

movieproject/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UPDATE</title>
</head>
<body>
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock %}
</body>
</html>